### ISSUE TITLE
More Giant crops and MUMPS

### ISSUE THREAD

**Issue by caspaas** [tlitookilakin/MUMPs#1]
hi!

whenever i add these 2 together it gives me 

[MUMPs] This mod failed in the GameLoop.GameLaunched event. Technical details:
HarmonyLib.HarmonyException: Patching exception in method virtual System.Void StardewValley.Crop::newDay(System.Int32 state, System.Int32 fertilizer, System.Int32 xTile, System.Int32 yTile, StardewValley.GameLocation environment)
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> InvalidProgramException: The JIT compiler encountered invalid IL code or an internal limitation.
   at Interop.Ole32.CoTaskMemFree(IntPtr ptr)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform.GetMethodHandle(MethodBase method)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.GetIdentifiable(MethodBase method)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.Pin(MethodBase method)
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at HarmonyLib.MethodPatcher.CreateReplacement(Dictionary`2& finalInstructions)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchClassProcessor.ProcessPatchJob(Job job)
   --- End of inner exception stack trace ---
   at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
   at HarmonyLib.PatchClassProcessor.Patch()
   at HarmonyLib.Harmony.<PatchAll>b__10_0(Type type)
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at MUMPs.ModEntry.Init(Object _, GameLaunchedEventArgs ev) in C:\Users\Wren\source\repos\MUMPs\MUMPs\ModEntry.cs:line 58
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

**Comment by tlitookilakin** [comment]
Thanks, looking into it

**Comment by tlitookilakin** [comment]
fixed by e236e0a3d2bfbbe3d8c676dcd2bc1bcb3b1aabfe.

**Comment by caspaas** [comment]
thanks for fixxing it !
but how do i compile a new version with the fix?

Sorry to ask this of you

**Comment by caspaas** [comment]
[MUMPs] Failed to retrieve hijacked pytk display device, attempting default
[MUMPs] This mod failed in the GameLoop.SaveLoaded event. Technical details:
NullReferenceException: Object reference not set to an instance of an object.
   at MUMPs.Props.LightingLayer.Reload() in C:\Users\Wren\source\repos\MUMPs\MUMPs\Props\LightingLayer.cs:line 41
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
   
   also you know where this is coming from ?

**Comment by tlitookilakin** [comment]
please make a separate issue with a complete log
