### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by martin66789** [tlitookilakin/MUMPs#4]
Hi,

Cape Stardew mod would use it.

MUMPS gives the following error:
"[11:03:52 TRACE MUMPs] Accessed mod-provided API (CustomOreNodes.CustomOreNodesAPI) for Custom Ore Nodes.
[11:03:52 TRACE MUMPs] Accessed mod-provided API (CustomResourceClumps.CustomResourceClumpsAPI) for Custom Resource Clumps.
[11:03:52 DEBUG MUMPs] Attempting to patch MinecartPatcher...
[11:03:52 WARN  MUMPs] Failed to find patch target. MinecartPatcher not patched.
[11:03:52 ERROR MUMPs] This mod failed in the GameLoop.GameLaunched event. Technical details: 
HarmonyLib.HarmonyException: Patching exception in method virtual System.Void StardewValley.Crop::newDay(System.Int32 state, System.Int32 fertilizer, System.Int32 xTile, System.Int32 yTile, StardewValley.GameLocation environment)
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> InvalidProgramException: The JIT compiler encountered invalid IL code or an internal limitation.
   at Interop.Ole32.CoTaskMemFree(IntPtr ptr)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform.GetMethodHandle(MethodBase method)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.GetIdentifiable(MethodBase method)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.Pin(MethodBase method)
   at MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   at HarmonyLib.MethodPatcher.CreateReplacement(Dictionary`2& finalInstructions)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchClassProcessor.ProcessPatchJob(Job job)
   --- End of inner exception stack trace ---
   at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
   at HarmonyLib.PatchClassProcessor.Patch()
   at HarmonyLib.Harmony.<PatchAll>b__10_0(Type type)
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at MUMPs.ModEntry.Init(Object _, GameLaunchedEventArgs ev) in C:\Users\Wren\source\repos\MUMPs\MUMPs\ModEntry.cs:line 58
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101"

Full SMAPI LOG
[https://smapi.io/log/cbc4c57adf42424b8cd97f8dc6d1aee9?format=RawView](url)

**Comment by tlitookilakin** [comment]
Once the game is FULLY LOADED, I need you to enter the following command into console-
`harmony_summary StardewValley.Crop::newDay`
and upload a new log afterwards.

You have a LOT of mods that modify the game code and I need to know which of those are conflicting with MUMPS's patch.

**Comment by martin66789** [comment]
[https://smapi.io/log/083378731d63409f97c8844645ef6e04?Page=3&PerPage=1000](url)

Harmony patches which match your search terms:

   StardewValley.Crop.newDay
      - spacechase0.DynamicGameAssets (prefix)
      - spacechase0.JsonAssets (transpiler)
      - spacechase0.MoreGiantCrops (transpiler)
      - tlitookilakin.mumps (postfix)

**Comment by tlitookilakin** [comment]
Thank you! looking into it now.

**Comment by tlitookilakin** [comment]
Try this build
[MUMPs 1.0.0-ALPHA-3.zip](https://github.com/tlitookilakin/MUMPs/files/12031465/MUMPs.1.0.0-ALPHA-3.zip)

**Comment by martin66789** [comment]
The error has been completely resolved.

**Comment by tlitookilakin** [comment]
sweet!
